{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptime-kuma.mysql.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "uptime-kuma.mysql.labels" . | nindent 4 }}
data:
  custom.cnf: |
    {{- .Values.mysql.config | nindent 4 }}
{{- end }}
